name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: pnpm
      run: corepack enable

    - name: Install
      run: pnpm i

    # - name: Lint
    #   run: npm run client:lint

    - name: Build
      run: pnpm run build

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: www.breizhtraining.bzh